export const GET_ORPHANS_LIST_INIT = 'GET_ORPHANS_LIST_INIT';

export const GET_ORPHANS_LIST_FAILURE = 'GET_ORPHANS_LIST_FAILURE';

export const GET_ORPHANS_LIST_SUCCESS = 'GET_ORPHANS_LIST_SUCCESS';
